// Comprehensive API catalog mapped to agents.
// tier: 'free' | 'freemium' | 'paid'
// mcp:  whether an official MCP server exists for Claude Desktop
//
// Each entry tells the app:
//  - which agents need this integration
//  - whether to show it as required vs optional
//  - free-tier reality so users know what they can try without paying
//  - the env var name we read at runtime (VITE_*) and the key prefix shape we expect

export const CATEGORIES = {
  brain:    { id: 'brain',    label: 'LLM Brain',          desc: 'The reasoning core — at least one is required for autonomous behavior.' },
  social:   { id: 'social',   label: 'Social & Marketing', desc: 'Profile audits, post scheduling, paid ads.' },
  outreach: { id: 'outreach', label: 'Outreach & Email',   desc: 'Cold email, sequences, and reply detection.' },
  sales:    { id: 'sales',    label: 'Sales & CRM',        desc: 'Prospect data, enrichment, pipeline tracking.' },
  dev:      { id: 'dev',      label: 'Development & Infra', desc: 'Repos, deploys, hosting, monitoring.' },
  pm:       { id: 'pm',       label: 'Project & Comms',    desc: 'Tickets, sprints, team chat, knowledge base.' },
  finance:  { id: 'finance',  label: 'Finance',            desc: 'Payments, banking, accounting.' },
  hr:       { id: 'hr',       label: 'HR & Recruiting',    desc: 'ATS, onboarding, time tracking.' },
  pr:       { id: 'pr',       label: 'PR & Media',         desc: 'Press distribution and journalist outreach.' },
};

export const APIS = [
  // ────────── BRAIN ──────────
  {
    id: 'anthropic', name: 'Anthropic (Claude)', category: 'brain', tier: 'paid',
    desc: 'Best general reasoning. Powers CEO decomposition + most agents.',
    envKey: 'VITE_ANTHROPIC_API_KEY', keyPrefix: 'sk-ant-',
    signupUrl: 'https://console.anthropic.com/', docsUrl: 'https://docs.anthropic.com/',
    pricing: '$3/M input · $15/M output (Claude 3.7 Sonnet)',
    freeTier: '$5 free credit on signup',
    mcp: 'host', // Claude itself hosts MCPs
    agents: ['ceo', 'cmo', 'cto', 'cso', 'coo', 'cfo', 'mktHead', 'contentLead', 'leadDev', 'devOps', 'salesHead', 'prMgr', 'hrHead', 'opsHead', 'finHead'],
    required: true,
  },
  {
    id: 'openai', name: 'OpenAI (GPT-4)', category: 'brain', tier: 'paid',
    desc: 'Alternative brain. Strong on structured output + function calling.',
    envKey: 'VITE_OPENAI_API_KEY', keyPrefix: 'sk-',
    signupUrl: 'https://platform.openai.com/', docsUrl: 'https://platform.openai.com/docs',
    pricing: '$2.50/M input · $10/M output (GPT-4o)',
    freeTier: 'No free credit (was deprecated)',
    mcp: false,
    agents: ['ceo', 'leadDev', 'salesHead'],
    alternativeTo: 'anthropic',
  },
  {
    id: 'groq', name: 'Groq', category: 'brain', tier: 'free',
    desc: 'Free, blazing-fast inference (Llama 3.3, Mixtral). Great for high-volume agent loops.',
    envKey: 'VITE_GROQ_API_KEY', keyPrefix: 'gsk_',
    signupUrl: 'https://console.groq.com/', docsUrl: 'https://console.groq.com/docs',
    pricing: 'Free tier: 30 req/min, 6K tokens/min',
    freeTier: 'Generous free tier — no card required',
    mcp: false,
    agents: ['mktHead', 'contentLead', 'opsHead', 'hrHead'],
  },
  {
    id: 'gemini', name: 'Google Gemini', category: 'brain', tier: 'freemium',
    desc: 'Free tier 1.5M tokens/day. Solid for content generation.',
    envKey: 'VITE_GEMINI_API_KEY', keyPrefix: 'AIza',
    signupUrl: 'https://aistudio.google.com/apikey', docsUrl: 'https://ai.google.dev/',
    pricing: 'Free up to 15 RPM; paid tier scales',
    freeTier: '1.5M tokens/day on Gemini 1.5 Flash — free',
    mcp: false,
    agents: ['contentLead', 'mktHead'],
  },
  {
    id: 'openrouter', name: 'OpenRouter', category: 'brain', tier: 'freemium',
    desc: 'One API for 200+ models. Good for routing different agents to cost-optimal models.',
    envKey: 'VITE_OPENROUTER_API_KEY', keyPrefix: 'sk-or-',
    signupUrl: 'https://openrouter.ai/', docsUrl: 'https://openrouter.ai/docs',
    pricing: 'Pay-per-token at provider rates + 5% margin',
    freeTier: 'Some models are 100% free (Llama, Gemma)',
    mcp: false,
    agents: ['ceo'],
  },

  // ────────── SOCIAL ──────────
  {
    id: 'instagram-graph', name: 'Instagram Graph API', category: 'social', tier: 'free',
    desc: 'Read your own profile, posts, reels, insights. Powers the Marketing Head audit.',
    envKey: 'VITE_INSTAGRAM_GRAPH_TOKEN',
    signupUrl: 'https://developers.facebook.com/', docsUrl: 'https://developers.facebook.com/docs/instagram-api/',
    pricing: 'Free',
    freeTier: 'Free for own/business accounts. Requires Facebook App + business account.',
    mcp: false,
    agents: ['mktHead', 'cmo'],
    setupNotes: 'Most painful setup — needs FB Developer App, IG Business account, long-lived token. Consider Apify instead for read-only.',
  },
  {
    id: 'apify', name: 'Apify (Instagram/TikTok scraper)', category: 'social', tier: 'freemium',
    desc: 'Easier alternative to Graph API. Scrape any public profile, reels, view counts.',
    envKey: 'VITE_APIFY_TOKEN', keyPrefix: 'apify_api_',
    signupUrl: 'https://apify.com/', docsUrl: 'https://docs.apify.com/',
    pricing: '$0.25 per 1K results typically',
    freeTier: '$5/mo free credit',
    mcp: false,
    agents: ['mktHead', 'salesHead', 'prMgr'],
    setupNotes: 'Recommended for scraping competitor accounts.',
  },
  {
    id: 'twitter', name: 'X (Twitter) API', category: 'social', tier: 'paid',
    desc: 'Post, search, and analyze tweets. Required for Twitter content automation.',
    envKey: 'VITE_TWITTER_BEARER_TOKEN',
    signupUrl: 'https://developer.twitter.com/', docsUrl: 'https://developer.twitter.com/en/docs',
    pricing: 'Basic $100/mo · Pro $5,000/mo',
    freeTier: 'Free tier is read-only and very limited (1,500 tweets/mo)',
    mcp: false,
    agents: ['contentLead', 'prMgr'],
  },
  {
    id: 'meta-ads', name: 'Meta Marketing API', category: 'social', tier: 'free',
    desc: 'Programmatically launch and optimize Instagram/Facebook ad campaigns.',
    envKey: 'VITE_META_ADS_TOKEN',
    signupUrl: 'https://developers.facebook.com/docs/marketing-api/', docsUrl: 'https://developers.facebook.com/docs/marketing-apis/',
    pricing: 'Free API · ad spend separate',
    freeTier: 'API is free; you pay for the ad spend itself',
    mcp: false,
    agents: ['mktHead'],
  },
  {
    id: 'google-ads', name: 'Google Ads API', category: 'social', tier: 'free',
    desc: 'Manage Google Ads campaigns programmatically.',
    envKey: 'VITE_GOOGLE_ADS_DEVELOPER_TOKEN',
    signupUrl: 'https://ads.google.com/home/tools/manager-accounts/', docsUrl: 'https://developers.google.com/google-ads/api/docs/start',
    pricing: 'Free API · ad spend separate',
    freeTier: 'API free; needs MCC account approval (~5 days)',
    mcp: false,
    agents: ['mktHead'],
  },

  // ────────── OUTREACH ──────────
  {
    id: 'resend', name: 'Resend', category: 'outreach', tier: 'freemium',
    desc: 'Modern transactional email. Best DX for AI-driven email sending.',
    envKey: 'VITE_RESEND_API_KEY', keyPrefix: 're_',
    signupUrl: 'https://resend.com/', docsUrl: 'https://resend.com/docs',
    pricing: 'Free 3K/mo · $20/mo for 50K',
    freeTier: '3,000 emails/month free',
    mcp: false,
    agents: ['salesHead', 'prMgr', 'hrHead'],
  },
  {
    id: 'gmail', name: 'Gmail API', category: 'outreach', tier: 'free',
    desc: 'Send/read from your Gmail account. Best for personal outreach.',
    envKey: 'VITE_GMAIL_OAUTH_TOKEN',
    signupUrl: 'https://console.cloud.google.com/', docsUrl: 'https://developers.google.com/gmail/api',
    pricing: 'Free',
    freeTier: 'Free up to 1B quota units/day',
    mcp: 'community',
    agents: ['salesHead', 'hrHead'],
  },
  {
    id: 'lemlist', name: 'Lemlist', category: 'outreach', tier: 'paid',
    desc: 'Cold email sequences with deliverability optimization.',
    envKey: 'VITE_LEMLIST_API_KEY',
    signupUrl: 'https://www.lemlist.com/', docsUrl: 'https://developer.lemlist.com/',
    pricing: '$59/mo per seat',
    freeTier: '14-day trial',
    mcp: false,
    agents: ['salesHead'],
  },

  // ────────── SALES ──────────
  {
    id: 'apollo', name: 'Apollo.io', category: 'sales', tier: 'freemium',
    desc: '275M+ contacts. Lead enrichment, email finding, sequences.',
    envKey: 'VITE_APOLLO_API_KEY',
    signupUrl: 'https://www.apollo.io/', docsUrl: 'https://apolloio.github.io/apollo-api-docs/',
    pricing: '$49-119/mo',
    freeTier: '50 mobile + 100 email credits/mo free',
    mcp: false,
    agents: ['salesHead'],
  },
  {
    id: 'clay', name: 'Clay', category: 'sales', tier: 'paid',
    desc: 'Multi-source enrichment. The "AI agent" tool for sales ops.',
    envKey: 'VITE_CLAY_API_KEY',
    signupUrl: 'https://www.clay.com/', docsUrl: 'https://docs.clay.com/',
    pricing: '$149/mo entry',
    freeTier: '14-day trial',
    mcp: false,
    agents: ['salesHead'],
  },
  {
    id: 'hunter', name: 'Hunter.io', category: 'sales', tier: 'freemium',
    desc: 'Email finder + verifier. Cheapest way to find work emails.',
    envKey: 'VITE_HUNTER_API_KEY',
    signupUrl: 'https://hunter.io/', docsUrl: 'https://hunter.io/api',
    pricing: '$49-499/mo',
    freeTier: '25 searches + 50 verifications/mo free',
    mcp: false,
    agents: ['salesHead'],
  },
  {
    id: 'hubspot', name: 'HubSpot CRM', category: 'sales', tier: 'freemium',
    desc: 'Free CRM for pipeline tracking. Generous free tier.',
    envKey: 'VITE_HUBSPOT_API_KEY',
    signupUrl: 'https://www.hubspot.com/', docsUrl: 'https://developers.hubspot.com/',
    pricing: 'Paid tiers from $20/mo',
    freeTier: 'Free CRM forever — unlimited contacts',
    mcp: 'community',
    agents: ['salesHead', 'cso'],
  },

  // ────────── DEV ──────────
  {
    id: 'github', name: 'GitHub API', category: 'dev', tier: 'free',
    desc: 'Repo management, PRs, Actions, Issues.',
    envKey: 'VITE_GITHUB_TOKEN', keyPrefix: 'ghp_',
    signupUrl: 'https://github.com/settings/tokens', docsUrl: 'https://docs.github.com/en/rest',
    pricing: 'Free',
    freeTier: 'Free unlimited for public repos. 5K req/hr authenticated.',
    mcp: 'official',
    agents: ['leadDev', 'devOps', 'cto'],
  },
  {
    id: 'vercel', name: 'Vercel', category: 'dev', tier: 'freemium',
    desc: 'Deploy Next.js/React apps. Lead Dev uses this for landing pages.',
    envKey: 'VITE_VERCEL_TOKEN',
    signupUrl: 'https://vercel.com/account/tokens', docsUrl: 'https://vercel.com/docs/rest-api',
    pricing: 'Hobby free · Pro $20/mo',
    freeTier: 'Hobby tier free for personal use',
    mcp: false,
    agents: ['leadDev'],
  },
  {
    id: 'netlify', name: 'Netlify', category: 'dev', tier: 'freemium',
    desc: 'Static site hosting + serverless functions. (You\'re using it now.)',
    envKey: 'VITE_NETLIFY_AUTH_TOKEN',
    signupUrl: 'https://app.netlify.com/user/applications', docsUrl: 'https://docs.netlify.com/api/get-started/',
    pricing: 'Free · Pro $19/mo',
    freeTier: '100GB bandwidth, 300 build min/mo free',
    mcp: false,
    agents: ['leadDev', 'devOps'],
  },
  {
    id: 'cloudflare', name: 'Cloudflare', category: 'dev', tier: 'freemium',
    desc: 'CDN, Workers, R2 storage, DNS.',
    envKey: 'VITE_CLOUDFLARE_API_TOKEN',
    signupUrl: 'https://dash.cloudflare.com/profile/api-tokens', docsUrl: 'https://developers.cloudflare.com/api/',
    pricing: 'Generous free tier · Workers $5/mo',
    freeTier: '100K Worker requests/day free',
    mcp: false,
    agents: ['devOps'],
  },
  {
    id: 'aws', name: 'AWS', category: 'dev', tier: 'freemium',
    desc: 'Full cloud. EC2, S3, Lambda, etc.',
    envKey: 'VITE_AWS_ACCESS_KEY_ID',
    signupUrl: 'https://aws.amazon.com/', docsUrl: 'https://docs.aws.amazon.com/',
    pricing: 'Pay-per-use',
    freeTier: '12 months free tier on signup',
    mcp: false,
    agents: ['devOps', 'cto'],
  },

  // ────────── PROJECT MGMT ──────────
  {
    id: 'linear', name: 'Linear', category: 'pm', tier: 'freemium',
    desc: 'Modern issue tracking. Best DX of any PM tool.',
    envKey: 'VITE_LINEAR_API_KEY', keyPrefix: 'lin_api_',
    signupUrl: 'https://linear.app/settings/api', docsUrl: 'https://developers.linear.app/',
    pricing: '$8/user/mo',
    freeTier: 'Free for up to 10 users',
    mcp: 'official',
    agents: ['hrHead', 'coo', 'opsHead', 'leadDev'],
  },
  {
    id: 'notion', name: 'Notion', category: 'pm', tier: 'freemium',
    desc: 'Docs, wikis, databases. Knowledge base for all agents.',
    envKey: 'VITE_NOTION_API_KEY', keyPrefix: 'secret_',
    signupUrl: 'https://www.notion.so/my-integrations', docsUrl: 'https://developers.notion.com/',
    pricing: 'Plus $10/user/mo',
    freeTier: 'Personal free; team blocks limited',
    mcp: 'official',
    agents: ['contentLead', 'opsHead', 'hrHead'],
  },
  {
    id: 'slack', name: 'Slack', category: 'pm', tier: 'freemium',
    desc: 'Team chat. Approvals, alerts, agent-to-human handoffs.',
    envKey: 'VITE_SLACK_BOT_TOKEN', keyPrefix: 'xoxb-',
    signupUrl: 'https://api.slack.com/apps', docsUrl: 'https://api.slack.com/',
    pricing: '$7.25/user/mo (Pro)',
    freeTier: 'Free tier with 90-day message history',
    mcp: 'official',
    agents: ['ceo', 'coo', 'opsHead'],
  },
  {
    id: 'jira', name: 'Jira', category: 'pm', tier: 'freemium',
    desc: 'Enterprise issue tracking.',
    envKey: 'VITE_JIRA_API_TOKEN',
    signupUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens', docsUrl: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3/',
    pricing: '$8.15/user/mo',
    freeTier: 'Free for up to 10 users',
    mcp: 'community',
    agents: ['hrHead', 'coo'],
  },

  // ────────── FINANCE ──────────
  {
    id: 'stripe', name: 'Stripe', category: 'finance', tier: 'free',
    desc: 'Payments + revenue tracking.',
    envKey: 'VITE_STRIPE_SECRET_KEY', keyPrefix: 'sk_',
    signupUrl: 'https://dashboard.stripe.com/apikeys', docsUrl: 'https://stripe.com/docs/api',
    pricing: '2.9% + 30¢ per transaction',
    freeTier: 'API is free · pay per transaction',
    mcp: 'official',
    agents: ['cfo', 'finHead'],
  },
  {
    id: 'plaid', name: 'Plaid', category: 'finance', tier: 'paid',
    desc: 'Bank account aggregation for cash flow tracking.',
    envKey: 'VITE_PLAID_SECRET',
    signupUrl: 'https://dashboard.plaid.com/', docsUrl: 'https://plaid.com/docs/',
    pricing: 'Pay-per-API-call',
    freeTier: 'Sandbox free; production billed',
    mcp: false,
    agents: ['finHead', 'cfo'],
  },
  {
    id: 'quickbooks', name: 'QuickBooks', category: 'finance', tier: 'paid',
    desc: 'Accounting + P&L automation.',
    envKey: 'VITE_QUICKBOOKS_OAUTH_TOKEN',
    signupUrl: 'https://developer.intuit.com/', docsUrl: 'https://developer.intuit.com/app/developer/qbo/docs/develop',
    pricing: 'From $30/mo',
    freeTier: 'Sandbox free for development',
    mcp: false,
    agents: ['finHead'],
  },

  // ────────── HR ──────────
  {
    id: 'greenhouse', name: 'Greenhouse', category: 'hr', tier: 'paid',
    desc: 'ATS for hiring pipelines.',
    envKey: 'VITE_GREENHOUSE_API_KEY',
    signupUrl: 'https://www.greenhouse.io/', docsUrl: 'https://developers.greenhouse.io/',
    pricing: 'Custom enterprise pricing',
    freeTier: 'No free tier',
    mcp: false,
    agents: ['hrHead'],
  },
  {
    id: 'bamboohr', name: 'BambooHR', category: 'hr', tier: 'paid',
    desc: 'HRIS for SMBs.',
    envKey: 'VITE_BAMBOOHR_API_KEY',
    signupUrl: 'https://www.bamboohr.com/', docsUrl: 'https://documentation.bamboohr.com/',
    pricing: 'From $5.25/employee/mo',
    freeTier: '7-day trial',
    mcp: false,
    agents: ['hrHead'],
  },

  // ────────── PR ──────────
  {
    id: 'haro', name: 'Connectively (HARO)', category: 'pr', tier: 'freemium',
    desc: 'Journalist queries — pitch your story for media coverage.',
    envKey: 'VITE_CONNECTIVELY_API_KEY',
    signupUrl: 'https://www.connectively.us/', docsUrl: 'https://www.connectively.us/api',
    pricing: '$148/mo Pro',
    freeTier: 'Free tier — limited submissions',
    mcp: false,
    agents: ['prMgr'],
  },
  {
    id: 'cision', name: 'Cision', category: 'pr', tier: 'paid',
    desc: 'PR distribution + journalist database.',
    envKey: 'VITE_CISION_API_KEY',
    signupUrl: 'https://www.cision.com/', docsUrl: 'https://www.cision.com/products/',
    pricing: 'Enterprise',
    freeTier: 'No free tier',
    mcp: false,
    agents: ['prMgr'],
  },
];

export const getApisByAgent = (agentId) => APIS.filter(a => a.agents?.includes(agentId));
export const getApisByCategory = (catId) => APIS.filter(a => a.category === catId);
export const getApi = (id) => APIS.find(a => a.id === id);

export const TIER_META = {
  free:     { label: 'Free',     color: '#16a34a', bg: '#dcfce7' },
  freemium: { label: 'Freemium', color: '#2563eb', bg: '#dbeafe' },
  paid:     { label: 'Paid',     color: '#a16207', bg: '#fef3c7' },
};
